### ISSUE TITLE
Larger font for handled device

### ISSUE THREAD

**Issue by hot22shot** [SamYStudiO/es-theme-next-pixel#10]
Hello,

I have a WaveShare GameHat (https://www.waveshare.com/game-hat.htm) with a pi3b+ and I use the 480p version of your theme and it's very nice.
Of course with a 3.5" LCD screen I set it up without info for SystemView and GameView.
Nonetheless the game view screen is stil unreadable, would it be possible to have a version with larger font for the gamelist ?

Cheers

**Comment by SamYStudiO** [comment]
Hi,
maybe you can try crt_small package et force recalbox to run in 4/3 ratio
This version use bigger fonts

**Comment by SamYStudiO** [comment]
I'm closing for now please reopen if you still have issues with 6.1

**Comment by Mhowser** [comment]
Hello, I have the Retroflag GPi case handheld and the UI elements are very small. Is there any way to scale them up?
picture provided:
![IMG_20220501_024243](https://user-images.githubusercontent.com/24195572/166140675-19d81545-4401-4a8a-804c-aa0355076a25.jpg)
