### ISSUE TITLE
Recalbox 6.0 (3b+) Emulstation dont reload with Theme v1.1

### ISSUE THREAD

**Issue by emulsion-io** [SamYStudiO/es-theme-next-pixel#11]
Hi, 

When i choose the 1.1 theme ( in 1080, 720 or 480p ) the emulstation stay on the black screen with logo,

But when I use the 1.0 theme no problem.

Recalbox is fresh install.

theme.xml contain a bad path, maybee...

Have a nice day,

**Comment by hot22shot** [comment]
1.1 is only for the unreleased Recalbox 6.1.
Download release 1.0 for Recalbox 6.0.

**Comment by emulsion-io** [comment]
Ok !

I dl 1.0 for 6.0 Recalbox and is Ok,

Thanks,
