### ISSUE TITLE
Screenshot picture overflows behind the video preview for some vertical arcade games.

### ISSUE THREAD

**Issue by KingKebab** [SamYStudiO/es-theme-next-pixel#13]
Hello,

On some vertical games, the screenshot picture is larger than the video capture resolution. So, it shows screenshot's part (at left and right) behind the video. And it's not very pretty.

I recorded a video sample : https://www.youtube.com/watch?v=IatG6KHB0TY

A black background behind the video element could enhance the appearance. But I don't think EmulationStation provide this feature.

**Comment by sbobbo** [comment]
I am also experiencing this.

On top of that, the none of the arcade or console overlays(that looks like the screens or w/e) are working in version 1.3. I have gone through all the documentation several times and I have no idea why they are missing.

**Comment by SamYStudiO** [comment]
Hello i'm aware about this and unfortunatly i can't do much about it. To get further on arcade and other few systems game screenshots/videos may have different ratios (4:3 16:9 ...) so i can't force any ratio here, this pb doesn't exist with console systems since i force resolution for screenshot and video to the same size. If i do this for arcade some screenshot and/or video may be distort.

**Comment by KingKebab** [comment]
I was able to fix the issue using &lt;showSnapshotNoVideo&gt;true&lt;/showSnapshotNoVideo&gt; and &lt;snapshotSource&gt;thumbnail&lt;/snapshotSource&gt; parameters with the &lt;video&gt; element.

Here is what it looks like on a EmulationStation theme I tinked :
https://youtu.be/PEeLadHaON8

To scrap media of my roms from the ScreenScraper server, I work with ARRM.

From the "Main Options" tab of this tool, I enable the "Activation of the recovery of 4 images" in the "Extra Tag" window and I set the "thumbnail" tag to "screenshot" in the "Screenscraper media" window. From the "Images Options" tab I tick "Mix", "Box 3D" and "Download video (video TAG)" options. And I set the "Mix model" to "Next_Pixel_720_arcade".

Then, in your gamelist.xml file you should have something like that :

```

...
<game>
		<path>./1942.zip</path>
		<name>1942 (revision b)</name>
		<desc>"1942" est le premier jeu d'une longue lignée d'avions américains bouffant du japonais, même si par la suite, les zéro devinrent des alliés dans les jeux suivant, combattant des ennemis non identifiés.
Assez difficile, je ne suis jamais allé très loin. J'ai tenté ma chance sur commodore 64, ce qui économisait quelques balles que je pus renvoyer à l'ennemi (hihihouhihouha le jeu de mots hé). bref, il est aujourd'hui assez vieillot. Je vous conseille donc de le télécharger pour l'histoire et de vous plonger plutôt sur "strikers 1945" qui bénéficie d'une dizaine d'années de savoir faire dans le domaine du shoot them up, largement tributaire de 1942.

</desc>
		<rating>0.8</rating>
		<releasedate>19840101T000000</releasedate>
		<developer>Capcom</developer>
		<publisher>Capcom</publisher>
		<genre>Shoot'em up / Vertical, Shoot'em Up</genre>
		<players>1-2</players>
		<image>./#snaps/1942_screenscraper_mix_arrm.png</image>
		<marquee>./#snaps/1942_screenscraper_wheel_arrm.png</marquee>
		<boxart>./#snaps/1942_screenscraper_boxart_arrm.png</boxart>
		<screenshot>./#snaps/1942_screenscraper_screenshot_arrm.png</screenshot>
		<mix>./#snaps/1942_screenscraper_mix_arrm.png</mix>
		<thumbnail>./#snaps/1942_screenscraper_screenshot_arrm.png</thumbnail>
		<video>./#records/1942_screenscraper_video_arrm.mp4</video>
		<playcount>0</playcount>
		<lastplayed />
		<md5 />
		<region>wor</region>
</game>
...
```

It's important to have this tags used like :
&lt;image&gt; element as main Mix picture (merging boxart, marquee, cartridge and screenshot)
&lt;thumbnail&gt; element as game screenshot
&lt;video&gt; element as game movie

Here you can find my custom theme for download and see how I did the trick in the /mame/theme.xml file : https://www.filehosting.org/file/details/844316/es-theme-alekfull_vertical.7z

I think watching the code to understand it, should be easier for you than a long speech.
Basically, I used a black mask to hide the TV area showing the screenshot in the Mix picture. And the &lt;showSnapshotNoVideo&gt; option show the snapshot (&lt;thumbnail&gt; tag) if the video can't be found.

```
     <video name="md_video">
         <pos>0.308 0.3685</pos>
         <maxSize>0.2005 0.2680</maxSize>
         <delay>0.0</delay>
         <showSnapshotNoVideo>true</showSnapshotNoVideo>
         <snapshotSource>thumbnail</snapshotSource>
         <zIndex>44</zIndex>  
     </video>
     
     <image name="blackscreen" extra="true">
         <path>./../_inc/images/black_background.png</path>
         <pos>0.208 0.235</pos>
         <size>0.200 0.268</size>
         <zIndex>42</zIndex>         
     </image>

```

Perhaps you will be able to employ my trick in your NextPixel theme. I know you have more technicals constraints to keep compatibility than me.
