### ISSUE TITLE
Could you add Arcade by system/manufacturer please?

### ISSUE THREAD

**Issue by esmith13** [SamYStudiO/es-theme-next-pixel#14]
Hi. Absolutely LOVE your theme! I have made modded versions of it for smaller screen systems as well as "Arcade specific" versions but unlike you I have NO artistic talent. I made my own version if the theme that supports system/manufacturer style display of arcade games, but in my version I just duplicate either mame or fbneo systems and rename them as needed and drop in logo.svg files for the proper logos taken from another theme. Any chance you could do them properly/officially in your theme, please? The systems in question are all based on mame2003 and are given the mame standardized names as follows:
capcom - (Pre CPS capcom games)
cave
cps1
cps2
cps3
dataeast
galaxian - (All games based on the galaxian board)
irem
kaneko
konami
midway
pacman - (All games based on pacman board)
pgm - (Poly Game Master)
psikyo
sega
seta
taito
technos
toaplan

If you would at all consider adding them, please feel free to download this zip file of logo.svg files specifically for the above: 
[Arcade Manufacturer Logos.zip](https://github.com/SamYStudiO/es-theme-next-pixel/files/4719190/Arcade.Manufacturer.Logos.zip)

Thank you in advance for your consideration!

**Comment by SamYStudiO** [comment]
Hello and sorry for late answer!
Unfurtunately i have no time for now adding thoses systems, if i have time later i let you know.
Sorry i guess this is not the answer you expected.
++
