### ISSUE TITLE
For RecalBox 7.0+, some missmatch in readme files ;-)

### ISSUE THREAD

**Issue by bozothegeek** [SamYStudiO/es-theme-next-pixel#15]
Hi SamYStudiO,

I saw that you are preparing the arrival of recalbox 7.0+... just for your info, some times the details go to use v1.3 (lisezmoi.txt) and other in v1.4 (readme.txt)... is it normal ?

Good job in all cases ;-)

Regards,

Valéry

**Comment by SamYStudiO** [comment]
Hello bozothegeek, 

Thx, this should be ok by now, let me know if you see more.
++
