### ISSUE TITLE
Thèmes pour systèmes virtuels

### ISSUE THREAD

**Issue by gcorly** [SamYStudiO/es-theme-next-pixel#19]
Salut, 
j'adore ton thème et je viens de passer sous la V7 de Recalbox, j'ai donc directement mis ton thème :)
par contre je trouve l'idée de Recalbox super de pouvoir avoir des systèmes virtuel, je vois que tu as préparé les auto-xxx dans ton thème mais ça pourrait être sympa d'avoir une image en lien avec le système virtuel justement, parce que je trouve que leurs icônes ne sont pas toujours explicites et je n'ose pas modifier ton thème pour ajouter des backgrounds ou autre.

j'ai aussi essayé de récupérer tes games.sh mais je dois mal m'y prendre, j'ai tous mes systèmes sans fond d'écran.
Je suis sous Raspberry PI 3

Dernière chose, dans ton ReadMe, les liens vers les téléchargements sont morts, il faut passer par le site pour avoir les thèmes, j'ai donc du mal à comprendre ce qu'il faudrait télécharger via la page "Code"

encore merci pour tout ce que tu fais, j'espère que tu le feras vite évoluer :)

**Comment by SamYStudiO** [comment]
Hello si tu es passé par ici pour le teléchargement, c'est une version de developpement (v2 du theme) non fonctionnele sur recalbox pour le moment. Si tu veux la derniere version fonctionnelle il faut passer par le site de recalbox ou par [ici](https://github.com/SamYStudiO/es-theme-next-pixel/releases/tag/v1.4)

la v2 aura la plupart des auto-xxx avec une image

++

**Comment by gcorly** [comment]
Salut, 

Merci pour ton retour rapide, c'est parfait :)

Envoyé de mon iPhone

Le 12 avr. 2021 à 01:04, Samuel Eminet ***@***.***> a écrit :

﻿
Hello si tu es passé par ici pour le teléchargement, c'est une version de developpement (v2 du theme) non fonctionnele sur recalbox pour le moment. Si tu veux la derniere version fonctionnelle il faut passer par le site de recalbox ou par ici

la v2 aura la plupart des auto-xxx avec une image

++
