### ISSUE TITLE
#Theme es-theme-next-pixel-1080p for recalbox 7.0+ doesn't work on recalbox 7.2

### ISSUE THREAD

**Issue by Burtonnak** [SamYStudiO/es-theme-next-pixel#20]
After Theme installation es-theme-next-pixel-1080p for recalbox 7.0+, Recalbox 7.2 system start and reboot when you try to navigate between console on the main page.

Configuration : 
Raspberry PI4 (4Go ram)

How to reproduce the bug : 
1- Install Recalbox 7.2
2- First time boot then
3- Put the theme on the theme repo
4- Choose the theme es-theme-next-pixel-1080p on the configuration menu
5- Reboot
6- Try to navigate

PS: This theme work very well on 7.1.1, and 7.1

**Comment by SamYStudiO** [comment]
It"s a known issue on Recalbox side, they're working on a fix
