### ISSUE TITLE
Recalboxx v7.2 not compatible

### ISSUE THREAD

**Issue by sol4ris33** [SamYStudiO/es-theme-next-pixel#22]
Hello,

It seems that nextPixel is not compatible with recalbox last release v7.2
When recalbox update is loaded, system is continuously rebooting device.....
Is it normal?

Thanks.

**Comment by siocone** [comment]
same here, i take the 720 theme than it runs

**Comment by sol4ris33** [comment]
Finally, it's OK with the last recalbox  update 7.2.1!
