### ISSUE TITLE
Scrape naomigd pas reconnu en tant que système arcade

### ISSUE THREAD

**Issue by Anklum** [SamYStudiO/es-theme-next-pixel#23]
Bonjour,

Lorsque j'utilise le fichier next_pixel_screenshot_title.xml dans Skraper pour obtenir des images mix, tout est OK à l'exception du système naomigd qui utilise l'image par défaut computer_flat.png (le système naomi lui est correctement affiché avec arcade.png).

Ci-dessous le contenu du fichier next_pixel_screenshot_title.xml lignes 85 et 86 :
_ARCADE arcade,atomiswave,daphne,fba,fbneo,mame,model3,naomi -->
Item IfSystem="IsInTheList:53,49,75,55,56">_

Quel numéro faudrait-il ajouter pour que naomigd soit reconnu en tant que système arcade?

Numéro qu'il faudra ensuite ajouter également ici j'imagine (lignes 10 et 11):
_DEFAULT COMPUTERS FLAT SCREEN -->
Item IfSystem="IsNotInTheList:26,40,41,80,48,106,115,2,3,104,67,109,29,122,130,23,13,87,27,1,14,142,70,31,114,72,58,57,107,22,19,20,4,108,105,59,16,18,64,111,65,43,42,37,93,66,91,113,116,117,118,131,135,213,123,218,205,141,144,73,79,77,76,53,49,75,55,56,17,129,86,217,21,9,12,10,52,28,146,15,25,82,219,221,208,237,211,61,207,102,11,45,46,220">_

**Comment by SamYStudiO** [comment]
Hello, sera résolu qur la 2.1 qui sort prochainement
